markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Debojeet Das
# Description of the Site
description: I do code!!
# URL of Image of the Site
site-image: #
# Keywords of the Site
site-keywords: Coding, Machine Learning, C, Python
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://res.cloudinary.com/daezpv949/image/upload/v1561320542/WiONHd_zYI4_Full_dotjzc.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: debojeetofficial@gmail.com
facebook_username: debojeetdas.official
twitter_username: thedebojeetdas
linkedin_username: /
github_username:  rickydebojeet

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Debojeet Das
# URL for the Image of the Author
author-image: https://res.cloudinary.com/daezpv949/image/upload/v1600682779/LRM_EXPORT_20180713_223650_pgcibp.jpg
# 60 Words About the Author
author-about: Hello there! People call me Debojeet Das. I'm basically a computer science student who is deeply interested in technology and I also want to learn more about computer science, how it works and how can we develop it to another level.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/rickydebojeet
# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
